/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Nft {
  'id' : NftId,
  'creator' : Principal,
  'listedAt' : Time,
  'owner' : [] | [Principal],
  'name' : string,
  'description' : string,
  'isSold' : boolean,
  'imageUrl' : string,
  'isFeatured' : boolean,
  'category' : string,
  'price' : bigint,
}
export type NftId = bigint;
export interface PlatformStats {
  'totalVolume' : bigint,
  'totalNftsSold' : bigint,
  'totalUsers' : bigint,
}
export interface ReferralStats {
  'totalBonus' : bigint,
  'referredCount' : bigint,
}
export interface T {
  'referralCode' : string,
  'balance' : bigint,
  'userId' : UserId,
  'walletAddress' : [] | [string],
  'earnings' : bigint,
  'referredBy' : [] | [UserId],
  'referralBonus' : bigint,
}
export type Time = bigint;
export type UserId = string;
export interface UserProfile {
  'referralCode' : string,
  'balance' : bigint,
  'userId' : UserId,
  'walletAddress' : [] | [string],
  'earnings' : bigint,
  'referredBy' : [] | [UserId],
  'referralBonus' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'adjustUserBalance' : ActorMethod<[Principal, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'banUser' : ActorMethod<[Principal], undefined>,
  'buyNft' : ActorMethod<[NftId], undefined>,
  'createNft' : ActorMethod<[Nft], undefined>,
  'getAllNfts' : ActorMethod<[], Array<Nft>>,
  'getAllUserProfiles' : ActorMethod<[], Array<UserProfile>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFeaturedNfts' : ActorMethod<[], Array<Nft>>,
  'getNft' : ActorMethod<[NftId], Nft>,
  'getPlatformStats' : ActorMethod<[], PlatformStats>,
  'getReferralStats' : ActorMethod<[UserId], ReferralStats>,
  'getUnsoldNfts' : ActorMethod<[], Array<Nft>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerProfile' : ActorMethod<[T], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setReferralBonus' : ActorMethod<[bigint], undefined>,
  'toggleFeatureNft' : ActorMethod<[NftId], boolean>,
  'updateCallerProfile' : ActorMethod<[T], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];