/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const NftId = IDL.Nat;
export const Time = IDL.Int;
export const Nft = IDL.Record({
  'id' : NftId,
  'creator' : IDL.Principal,
  'listedAt' : Time,
  'owner' : IDL.Opt(IDL.Principal),
  'name' : IDL.Text,
  'description' : IDL.Text,
  'isSold' : IDL.Bool,
  'imageUrl' : IDL.Text,
  'isFeatured' : IDL.Bool,
  'category' : IDL.Text,
  'price' : IDL.Nat,
});
export const UserId = IDL.Text;
export const UserProfile = IDL.Record({
  'referralCode' : IDL.Text,
  'balance' : IDL.Nat,
  'userId' : UserId,
  'walletAddress' : IDL.Opt(IDL.Text),
  'earnings' : IDL.Nat,
  'referredBy' : IDL.Opt(UserId),
  'referralBonus' : IDL.Nat,
});
export const PlatformStats = IDL.Record({
  'totalVolume' : IDL.Nat,
  'totalNftsSold' : IDL.Nat,
  'totalUsers' : IDL.Nat,
});
export const ReferralStats = IDL.Record({
  'totalBonus' : IDL.Nat,
  'referredCount' : IDL.Nat,
});
export const T = IDL.Record({
  'referralCode' : IDL.Text,
  'balance' : IDL.Nat,
  'userId' : UserId,
  'walletAddress' : IDL.Opt(IDL.Text),
  'earnings' : IDL.Nat,
  'referredBy' : IDL.Opt(UserId),
  'referralBonus' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'adjustUserBalance' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'banUser' : IDL.Func([IDL.Principal], [], []),
  'buyNft' : IDL.Func([NftId], [], []),
  'createNft' : IDL.Func([Nft], [], []),
  'getAllNfts' : IDL.Func([], [IDL.Vec(Nft)], ['query']),
  'getAllUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFeaturedNfts' : IDL.Func([], [IDL.Vec(Nft)], ['query']),
  'getNft' : IDL.Func([NftId], [Nft], ['query']),
  'getPlatformStats' : IDL.Func([], [PlatformStats], ['query']),
  'getReferralStats' : IDL.Func([UserId], [ReferralStats], ['query']),
  'getUnsoldNfts' : IDL.Func([], [IDL.Vec(Nft)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerProfile' : IDL.Func([T], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setReferralBonus' : IDL.Func([IDL.Nat], [], []),
  'toggleFeatureNft' : IDL.Func([NftId], [IDL.Bool], []),
  'updateCallerProfile' : IDL.Func([T], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const NftId = IDL.Nat;
  const Time = IDL.Int;
  const Nft = IDL.Record({
    'id' : NftId,
    'creator' : IDL.Principal,
    'listedAt' : Time,
    'owner' : IDL.Opt(IDL.Principal),
    'name' : IDL.Text,
    'description' : IDL.Text,
    'isSold' : IDL.Bool,
    'imageUrl' : IDL.Text,
    'isFeatured' : IDL.Bool,
    'category' : IDL.Text,
    'price' : IDL.Nat,
  });
  const UserId = IDL.Text;
  const UserProfile = IDL.Record({
    'referralCode' : IDL.Text,
    'balance' : IDL.Nat,
    'userId' : UserId,
    'walletAddress' : IDL.Opt(IDL.Text),
    'earnings' : IDL.Nat,
    'referredBy' : IDL.Opt(UserId),
    'referralBonus' : IDL.Nat,
  });
  const PlatformStats = IDL.Record({
    'totalVolume' : IDL.Nat,
    'totalNftsSold' : IDL.Nat,
    'totalUsers' : IDL.Nat,
  });
  const ReferralStats = IDL.Record({
    'totalBonus' : IDL.Nat,
    'referredCount' : IDL.Nat,
  });
  const T = IDL.Record({
    'referralCode' : IDL.Text,
    'balance' : IDL.Nat,
    'userId' : UserId,
    'walletAddress' : IDL.Opt(IDL.Text),
    'earnings' : IDL.Nat,
    'referredBy' : IDL.Opt(UserId),
    'referralBonus' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'adjustUserBalance' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'banUser' : IDL.Func([IDL.Principal], [], []),
    'buyNft' : IDL.Func([NftId], [], []),
    'createNft' : IDL.Func([Nft], [], []),
    'getAllNfts' : IDL.Func([], [IDL.Vec(Nft)], ['query']),
    'getAllUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFeaturedNfts' : IDL.Func([], [IDL.Vec(Nft)], ['query']),
    'getNft' : IDL.Func([NftId], [Nft], ['query']),
    'getPlatformStats' : IDL.Func([], [PlatformStats], ['query']),
    'getReferralStats' : IDL.Func([UserId], [ReferralStats], ['query']),
    'getUnsoldNfts' : IDL.Func([], [IDL.Vec(Nft)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerProfile' : IDL.Func([T], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setReferralBonus' : IDL.Func([IDL.Nat], [], []),
    'toggleFeatureNft' : IDL.Func([NftId], [IDL.Bool], []),
    'updateCallerProfile' : IDL.Func([T], [], []),
  });
};

export const init = ({ IDL }) => { return []; };