/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type UserId = string;
export type Time = bigint;
export interface Nft {
    id: NftId;
    creator: Principal;
    listedAt: Time;
    owner?: Principal;
    name: string;
    description: string;
    isSold: boolean;
    imageUrl: string;
    isFeatured: boolean;
    category: string;
    price: bigint;
}
export interface T {
    referralCode: string;
    balance: bigint;
    userId: UserId;
    walletAddress?: string;
    earnings: bigint;
    referredBy?: UserId;
    referralBonus: bigint;
}
export interface ReferralStats {
    totalBonus: bigint;
    referredCount: bigint;
}
export type NftId = bigint;
export interface PlatformStats {
    totalVolume: bigint;
    totalNftsSold: bigint;
    totalUsers: bigint;
}
export interface UserProfile {
    referralCode: string;
    balance: bigint;
    userId: UserId;
    walletAddress?: string;
    earnings: bigint;
    referredBy?: UserId;
    referralBonus: bigint;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    adjustUserBalance(user: Principal, amount: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    banUser(user: Principal): Promise<void>;
    buyNft(id: NftId): Promise<void>;
    createNft(input: Nft): Promise<void>;
    getAllNfts(): Promise<Array<Nft>>;
    getAllUserProfiles(): Promise<Array<UserProfile>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getFeaturedNfts(): Promise<Array<Nft>>;
    getNft(id: NftId): Promise<Nft>;
    getPlatformStats(): Promise<PlatformStats>;
    getReferralStats(userId: UserId): Promise<ReferralStats>;
    getUnsoldNfts(): Promise<Array<Nft>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    registerProfile(profile: T): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setReferralBonus(amount: bigint): Promise<void>;
    toggleFeatureNft(id: NftId): Promise<boolean>;
    updateCallerProfile(updated: T): Promise<void>;
}
import type { Nft as _Nft, NftId as _NftId, T as _T, Time as _Time, UserId as _UserId, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async adjustUserBalance(arg0: Principal, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adjustUserBalance(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adjustUserBalance(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async banUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.banUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.banUser(arg0);
            return result;
        }
    }
    async buyNft(arg0: NftId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.buyNft(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.buyNft(arg0);
            return result;
        }
    }
    async createNft(arg0: Nft): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createNft(to_candid_Nft_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createNft(to_candid_Nft_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getAllNfts(): Promise<Array<Nft>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllNfts();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllNfts();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUserProfiles(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUserProfiles();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUserProfiles();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFeaturedNfts(): Promise<Array<Nft>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeaturedNfts();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeaturedNfts();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNft(arg0: NftId): Promise<Nft> {
        if (this.processError) {
            try {
                const result = await this.actor.getNft(arg0);
                return from_candid_Nft_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNft(arg0);
            return from_candid_Nft_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPlatformStats(): Promise<PlatformStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlatformStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlatformStats();
            return result;
        }
    }
    async getReferralStats(arg0: UserId): Promise<ReferralStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getReferralStats(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReferralStats(arg0);
            return result;
        }
    }
    async getUnsoldNfts(): Promise<Array<Nft>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUnsoldNfts();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUnsoldNfts();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async registerProfile(arg0: T): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerProfile(to_candid_T_n17(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerProfile(to_candid_T_n17(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n19(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n19(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setReferralBonus(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setReferralBonus(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setReferralBonus(arg0);
            return result;
        }
    }
    async toggleFeatureNft(arg0: NftId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleFeatureNft(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleFeatureNft(arg0);
            return result;
        }
    }
    async updateCallerProfile(arg0: T): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCallerProfile(to_candid_T_n17(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCallerProfile(to_candid_T_n17(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_Nft_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Nft): Nft {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserId]): UserId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n10(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    referralCode: string;
    balance: bigint;
    userId: _UserId;
    walletAddress: [] | [string];
    earnings: bigint;
    referredBy: [] | [_UserId];
    referralBonus: bigint;
}): {
    referralCode: string;
    balance: bigint;
    userId: UserId;
    walletAddress?: string;
    earnings: bigint;
    referredBy?: UserId;
    referralBonus: bigint;
} {
    return {
        referralCode: value.referralCode,
        balance: value.balance,
        userId: value.userId,
        walletAddress: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.walletAddress)),
        earnings: value.earnings,
        referredBy: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.referredBy)),
        referralBonus: value.referralBonus
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _NftId;
    creator: Principal;
    listedAt: _Time;
    owner: [] | [Principal];
    name: string;
    description: string;
    isSold: boolean;
    imageUrl: string;
    isFeatured: boolean;
    category: string;
    price: bigint;
}): {
    id: NftId;
    creator: Principal;
    listedAt: Time;
    owner?: Principal;
    name: string;
    description: string;
    isSold: boolean;
    imageUrl: string;
    isFeatured: boolean;
    category: string;
    price: bigint;
} {
    return {
        id: value.id,
        creator: value.creator,
        listedAt: value.listedAt,
        owner: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.owner)),
        name: value.name,
        description: value.description,
        isSold: value.isSold,
        imageUrl: value.imageUrl,
        isFeatured: value.isFeatured,
        category: value.category,
        price: value.price
    };
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Nft>): Array<Nft> {
    return value.map((x)=>from_candid_Nft_n6(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserProfile>): Array<UserProfile> {
    return value.map((x)=>from_candid_UserProfile_n10(_uploadFile, _downloadFile, x));
}
function to_candid_Nft_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Nft): _Nft {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_T_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: T): _T {
    return to_candid_record_n18(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n18(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    referralCode: string;
    balance: bigint;
    userId: UserId;
    walletAddress?: string;
    earnings: bigint;
    referredBy?: UserId;
    referralBonus: bigint;
}): {
    referralCode: string;
    balance: bigint;
    userId: _UserId;
    walletAddress: [] | [string];
    earnings: bigint;
    referredBy: [] | [_UserId];
    referralBonus: bigint;
} {
    return {
        referralCode: value.referralCode,
        balance: value.balance,
        userId: value.userId,
        walletAddress: value.walletAddress ? candid_some(value.walletAddress) : candid_none(),
        earnings: value.earnings,
        referredBy: value.referredBy ? candid_some(value.referredBy) : candid_none(),
        referralBonus: value.referralBonus
    };
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: NftId;
    creator: Principal;
    listedAt: Time;
    owner?: Principal;
    name: string;
    description: string;
    isSold: boolean;
    imageUrl: string;
    isFeatured: boolean;
    category: string;
    price: bigint;
}): {
    id: _NftId;
    creator: Principal;
    listedAt: _Time;
    owner: [] | [Principal];
    name: string;
    description: string;
    isSold: boolean;
    imageUrl: string;
    isFeatured: boolean;
    category: string;
    price: bigint;
} {
    return {
        id: value.id,
        creator: value.creator,
        listedAt: value.listedAt,
        owner: value.owner ? candid_some(value.owner) : candid_none(),
        name: value.name,
        description: value.description,
        isSold: value.isSold,
        imageUrl: value.imageUrl,
        isFeatured: value.isFeatured,
        category: value.category,
        price: value.price
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
